### ISSUE TITLE
Who wants to maintain this repository?

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/docker-node#1]
This repository was originally created by me, but I'm not a NodeJS guy and did not update it for a while.

I think nobody is really using this Docker image?

@prayerslayer do you want to maintain this Docker image or know anybody who would?

Otherwise I would propose deleting this GitHub repository.. :hourglass_flowing_sand:

**Comment by prayerslayer** [comment]
Why not :smiley:

**Comment by kgalli** [comment]
@hjacobs I could also help maintaining this. It seems reasonable for me to maintain this as a part of stups because I have to do it anyway for my team. So what do you think? @prayerslayer I assume it is the same for you, right?

**Comment by hjacobs** [comment]
@prayerslayer I added you: https://github.com/zalando/docker-node/blob/master/MAINTAINERS
@kgalli can you do a PR with your name + email in MAINTAINERS please? Thanks!
