### ISSUE TITLE
Idea for getting feedback and making these projects AUAP (as useful as possible)

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando-stups/docker-node#16]
I am wondering if you all would be open to asking other Zalando engineers for their feedback on these projects before we write READMEs, move, or do anything else with them. I have a feedback form ready for this that I've been using to help the owners of other project owners get inpu; all I would need from you would be the names of some people whose feedback you'd find most valuable. We can do it ASAP if you agree.

**Comment by kgalli** [comment]
Getting feedback to make this project more useful sounds like a good idea in general. What I do not get is the `these projects` and before `we write READMEs, move ...`. Do you referring to this project? Who is `we`?

For me it would be useful to know who is using this project. Then I can start a conversation to make this project even more useful. Ideas?

**Comment by lasomethingsomething** [comment]
Forwarded email with more info to @kgalli and came up with a small plan :)
