### ISSUE TITLE
name change request b/c of Docker guidelines

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando-stups/docker-node#23]
Requesting a name change in light of [this](https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle) and related email thread.

**Comment by kgalli** [comment]
Ok I recommend `node-docker`.

**Comment by lasomethingsomething** [comment]
@kgalli  I've asked our legal team if this is doable; don't want to risk it. Will let you know ASAP.

**Comment by lasomethingsomething** [comment]
Hi @kgalli: I emailed internally a note from our legal team addressing this topic and cc'ed you; check it out. :)
