### ISSUE TITLE
Image for Node 4.2.0 (LTS)

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/docker-node#3]

**Comment by kgalli** [comment]
@prayerslayer see #5. Is this what you are looking for? Any ideas? If you are fine with that I will add support for 5.1 in the same manor.

**Comment by prayerslayer** [comment]
Thanks for the PR. Unfortunately I can't try this as-is on a Mac (there is no `sha256sum`, for instance). Looks good otherwise, maybe @hjacobs can verify.

One thing though: I'd prefer to have a recent version of NPM (3.x) installed as well.

**Comment by kgalli** [comment]
@prayerslayer node v5.1.1 comes with npm 3.3.12. So if this is not a big deal I would prefer to keep it simple and refer to use 5.1.1. Any thoughts?

In regard to the `sha256sum`: This shouldn't be a problem because the docker host will run the command during the build so you can test it by just building the image, right?  Or did I get something wrong here. If I'm mistaken just ignore my comment ;-)

**Comment by prayerslayer** [comment]
Since the Docker host runs on my machine I can't build the image because there is no `sha256sum` on my platform :smiley: What's the argument against installing npm 3.x for Node 4 as well?

**Comment by kgalli** [comment]
Ah I thought you running your docker on a Mac (typically docker-engine on boot2docker). Anyhow in regard to the npm version my argument is just that it is a little bit more to maintain. We have to decide which version should be used. But maybe we can just add `RUN npm install npm -g` at the end of the `Dockerfile` and everything is fine. If you see no problem in the decision making for the npm version we can just add it to the `Dockerfile`.

**Comment by prayerslayer** [comment]
Just installing the latest npm would be fine by me.

**Comment by kgalli** [comment]
Last thought about the npm version: Please have a look at this https://github.com/nodejs/docker-node/issues/72 issue.

**Comment by prayerslayer** [comment]
How about pinning a current version, e.g. `3.3.12` or whatever? Then we don't break things accidentally on a new release.

**Comment by kgalli** [comment]
Yap that sounds like a good compromise. I will add this to the #5 and #7 and you can merge them ;-).

**Comment by prayerslayer** [comment]
Will close as there is an image for 4.2.
