### ISSUE TITLE
npm@5

### ISSUE THREAD

**Issue by shuhei** [zalando-stups/docker-node#33]
npm@5 was released with lots of nice features and better performance.

http://blog.npmjs.org/post/161276872334/npm5-is-now-npmlatest

Does it make sense to update it in `stable`?

**Comment by shuhei** [comment]
I tried to do it in my own `Dockerfile` that is `FROM` this image, but it didn't work of this issue.

https://github.com/npm/npm/issues/15558

**Comment by harti2006** [comment]
@shuhei Would we run into the same issue, when merging your Pull Request?

**Comment by shuhei** [comment]
@harti2006 No, we won't because the issue happens when we install `npm@5` after installing Node.js. It won't happen **somehow** when we install `npm@5` in the same `RUN` as Node.js installation.

I tested it on my local and it works, but I had to change `npm cache clear` to `npm cache clean --force` because of the following error. (`npm cache clear` is an alias for `npm cache clean`.)

```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-14T15_43_06_856Z-debug.log
```

The reason for it is documented in https://docs.npmjs.com/cli/cache#details
